const WULWYN_AVATAR = "https://scontent.fmlw1-2.fna.fbcdn.net/v/t1.6435-9/53121401_10156204857453437_4904719181628309504_n.jpg?_nc_cat=110&ccb=1-7&_nc_sid=53a332&_nc_eui2=AeHM7VGP9lGvyVYSK7M-N7OPtyAmpe0yAEC3ICal7TIAQAlKnT9aru1Vra9ERu2ERftuf6IhMNQco4jjEhKBidka&_nc_ohc=SYJ_JtOEynwQ7kNvwEvzNt7&_nc_oc=Adr07kDph0gtEgDOQvhk0fPuJfD8yIQCW-tRlQntnwr2NJWgcB0da0ukKWRA-_lfK4s&_nc_zt=23&_nc_ht=scontent.fmlw1-2.fna&_nc_gid=leeCcpZhuqHH2j4XhF0Row&_nc_ss=7a32e&oh=00_AfzRDlNsrFWbsEoG0PgHvPw2I3IJDZvA7zUIBbRjWOgeCw&oe=69E7DA12"

export const teamMembers = [
    {
        id: "victor",
        name: "Victor Edet Coleman",
        role: "Founder & CTO",
        title: "Chief Technology Officer",
        badge: "01",
        image: "/Team/VICTOR.jpeg",
        photos: [
            { id: "01", image: "/Team/VICTOR.jpeg", caption: "CTO" },
        ],
        tagline: "3D Software Engineer · Founder & CTO of HUIX-2099",
        bio: "Chief Technology Officer driving HUIX-2099's technical vision. Architects and builds HUIX-HORIZEN and Virtual Past Liberia—platforms that enable Liberia and the region to imagine, prototype, and build the future through XR, 3D visualization, and immersive systems.",
        focus: "XR · 3D Visualization · Systems Architecture · AI Integration",
        location: "Monrovia, Liberia",
        email: "huixtech2099@gmail.com",
        status: "Technical Leadership · R&D · Product Architecture",
        linkedin: "https://www.linkedin.com/in/victor-coleman-4731701a5/",
        facebook: "https://www.facebook.com/victor.coleman.745874",
        phone: "+231776800064, +231887544923",
        googleSearch: "https://www.google.com/search?q=huix+2099+victor&oq=huix+2099+victor&gs_lcrp=EgZjaHJvbWUyBggAEEUYOTIGCAEQIxgnMgcIAhAAGO8FMgcIAxAAGO8FMgcIBBAAGO8FMgcIBRAAGO8FMgcIBhAAGO8F0gEINTg3OWowajeoAgCwAgA&sourceid=chrome&ie=UTF-8"
    },
    {
        id: "wulwyn",
        name: "Wulwyn Porte L",
        role: "CEO & Co-founder & Investor",
        title: "Chief Executive Officer",
        badge: "02",
        image: WULWYN_AVATAR,
        photos: [{ id: "01", image: WULWYN_AVATAR, caption: "CEO" }],
        tagline: "CEO & Co-founder · Strategic Lead & Investor",
        bio: "Chief Executive Officer steering HUIX-2099's business strategy and growth. Co-founder and lead investor driving partnerships, funding, and market expansion for Liberia's next-generation technology company.",
        focus: "Strategy · Business Development · Investment",
        location: "Monrovia, Liberia",
        email: "huixtech2099@gmail.com",
        status: "Executive Leadership · Partnerships · Growth",
        linkedin: null,
        facebook: null,
        phone: null,
        googleSearch: null
    },
    {
        id: "jboy",
        name: "Jboy",
        role: "Playable Protagonist",
        title: "Main Character",
        badge: "03",
        image: "/products/Monrovia_hustle_Demo_Campane/cast_concept/Dominc%20Rockson.jpeg",
        photos: [
            { id: "01", image: "/products/Monrovia_hustle_Demo_Campane/cast_concept/Dominc%20Rockson.jpeg", caption: "Dominic Rockson (Voice Talent)" }
        ],
        tagline: "Sidewalk calculus",
        bio: "Twenty-four on a thin wage. Carey and Benson know his stride — hustle as survival math, receipts as morality. Jboy is brought to life by the voice talent of Dominic Rockson, whose performance captures the raw energy and cultural depth of Monrovia's streets.",
        focus: "Survival · Street Knowledge",
        location: "Monrovia, Liberia",
        email: "huixtech2099@gmail.com",
        status: "Active · Character Profile",
        linkedin: null,
        facebook: "https://www.facebook.com/profile.php?id=61572485499528",
        phone: null,
        googleSearch: null
    },
    {
        id: "arthur-kollie",
        name: "Arthur B. Kollie",
        role: "Cast Concept · HUIX Archive",
        title: "HUIX Archive",
        badge: "04",
        image: "/products/Monrovia_hustle_Demo_Campane/cast_concept/Arthur%20B.%20Kollie.jpeg",
        photos: [{ id: "01", image: "/products/Monrovia_hustle_Demo_Campane/cast_concept/Arthur%20B.%20Kollie.jpeg", caption: "Arthur" }],
        tagline: "Concept Tier 01",
        bio: "A key figure in the Monrovia Hustle narrative landscape, shaping the city's social and political undercurrents. Representing the established weight of the city, his concept points toward high-stakes interactions and structural pressure.",
        focus: "Narrative · Influence",
        location: "Monrovia, Liberia",
        email: "huixtech2099@gmail.com",
        status: "Concept · HUIX Archive",
        linkedin: null,
        facebook: "https://www.facebook.com/profile.php?id=61572485499528",
        phone: null,
        googleSearch: null
    },
    {
        id: "david",
        name: "David Neor Jr.",
        role: "Voice Actor · DC",
        title: "Monrovia Hustle 3D — DC Young",
        badge: "05",
        image: "/products/Monrovia_hustle_Demo_Campane/cast_concept/David%20Neor%20Jr.png",
        photos: [
            {
                id: "01",
                image: "/products/Monrovia_hustle_Demo_Campane/cast_concept/David%20Neor%20Jr.png",
                caption: "David Neor Jr. (voice — DC)",
            },
        ],
        tagline: "Street energy · mission spine",
        bio: "David Neor Jr. voices DC (DC Young) in Monrovia Hustle 3D — part of the Tenneh phone thread and street-facing hustle beats where tone, timing, and credibility have to land in one take.",
        focus: "Voice · Performance · Urban drama",
        location: "Monrovia, Liberia",
        email: "huixtech2099@gmail.com",
        status: "Voice Talent · HUIX Archive",
        linkedin: null,
        facebook: "https://www.facebook.com/profile.php?id=61572485499528",
        phone: null,
        googleSearch: null
    },
    {
        id: "johnette-talkpa",
        name: "Johnette Talkpa",
        role: "Voice Actor · Angel",
        title: "Monrovia Hustle 3D — Angel",
        badge: "06",
        image: "/products/Monrovia_hustle_Demo_Campane/cast_concept/Johnette%20Talkpa.png",
        photos: [
            {
                id: "01",
                image: "/products/Monrovia_hustle_Demo_Campane/cast_concept/Johnette%20Talkpa.png",
                caption: "Johnette Talkpa (voice — Angel)",
            },
        ],
        tagline: "Love priced in LD",
        bio: "Johnette Talkpa voices Angel in Monrovia Hustle 3D — Jboy's ex and emotional anchor where stability, ambition, and receipts collide. Her performance carries tenderness, exhaustion, and truth; the fallout that strands Jboy on the pavement is chapter-one gravity, not melodrama wallpaper.",
        focus: "Voice · Performance · Character tone",
        location: "Monrovia, Liberia",
        email: "huixtech2099@gmail.com",
        status: "Voice Talent · HUIX Archive",
        linkedin: null,
        facebook: "https://www.facebook.com/profile.php?id=61572485499528",
        phone: null,
        googleSearch: null,
    },
    {
        id: "thomas",
        name: "Thomas",
        role: "Street Operator · Connect",
        title: "Connect",
        badge: "07",
        image: "/products/Monrovia_hustle_Demo_Campane/images/WhatsApp%20Image%202026-05-04%20at%2011.57.51%20PM.jpeg",
        photos: [{ id: "01", image: "/products/Monrovia_hustle_Demo_Campane/images/WhatsApp%20Image%202026-05-04%20at%2011.57.51%20PM.jpeg", caption: "Thomas" }],
        tagline: "Fast talk, slower trust",
        bio: "Knows every shortcut between Broad and Benson; runs errands into favours — the kind that teach you downtown doesn't forgive noise. Expect branching missions that treat him like a hinge: help him, fleece him, or ghost him.",
        focus: "Logistics · Intelligence",
        location: "Monrovia, Liberia",
        email: "huixtech2099@gmail.com",
        status: "Operator · HUIX Archive",
        linkedin: null,
        facebook: "https://www.facebook.com/profile.php?id=61572485499528",
        phone: null,
        googleSearch: null
    },
    {
        id: "jonnet",
        name: "Jonnet",
        role: "Network · Pressure / Payoff",
        title: "Corner Memory",
        badge: "08",
        image: "/products/Monrovia_hustle_Demo_Campane/images/WhatsApp%20Image%202026-05-04%20at%2011.57.52%20PM.jpeg",
        photos: [{ id: "01", image: "/products/Monrovia_hustle_Demo_Campane/images/WhatsApp%20Image%202026-05-04%20at%2011.57.52%20PM.jpeg", caption: "Jonnet" }],
        tagline: "Corner memory",
        bio: "Holds rumours like currency — who owes, who flips phones, whose cousin heard Uncle Flomo's desk creak. Use her intel to stack LD or gamble reputation; epic beats land when alley gossip upgrades into storyline collision.",
        focus: "Information · Rumours",
        location: "Monrovia, Liberia",
        email: "huixtech2099@gmail.com",
        status: "Network · HUIX Archive",
        linkedin: null,
        facebook: "https://www.facebook.com/profile.php?id=61572485499528",
        phone: null,
        googleSearch: null
    },
    {
        id: "jerry-kollie",
        name: "Jerry D Kollie",
        role: "Voice Actor · Cast Concept",
        title: "Voice Talent",
        badge: "09",
        image: "/products/Monrovia_hustle_Demo_Campane/cast_concept/Jerry%20D%20Kollie.png",
        photos: [{ id: "01", image: "/products/Monrovia_hustle_Demo_Campane/cast_concept/Jerry%20D%20Kollie.png", caption: "Jerry" }],
        tagline: "Voice talent · Cast concept",
        bio: "Jerry D Kollie is a key part of the Monrovia Hustle voice cast, contributing his unique vocal style to the urban RPG landscape of HUIX-2099.",
        focus: "Voice Acting · Performance",
        location: "Monrovia, Liberia",
        email: "huixtech2099@gmail.com",
        status: "Voice Talent · HUIX Archive",
        linkedin: null,
        facebook: "https://www.facebook.com/profile.php?id=61572485499528",
        phone: null,
        googleSearch: null
    },
    {
        id: "felix-sowoma",
        name: "Felix J. K. Sowoma",
        role: "Voice Actor · Jayboy's uncle",
        title: "Monrovia Hustle 3D — Family arc",
        badge: "10",
        image: "/products/Monrovia_hustle_Demo_Campane/cast_concept/felix%20J.%20K.%20Sowoma.png",
        photos: [
            {
                id: "01",
                image: "/products/Monrovia_hustle_Demo_Campane/cast_concept/felix%20J.%20K.%20Sowoma.png",
                caption: "Felix J. K. Sowoma (voice — Jayboy's uncle)",
            },
        ],
        tagline: "Family weight · street wisdom",
        bio: "Felix J. K. Sowoma voices Jayboy's uncle in Monrovia Hustle 3D — the family pull between protection, expectation, and the corner's fast-money gravity. His read anchors the pressure that makes Monrovia's hustle feel lived-in, not abstract.",
        focus: "Voice · Drama · Family stakes",
        location: "Monrovia, Liberia",
        email: "huixtech2099@gmail.com",
        status: "Voice Talent · HUIX Archive",
        linkedin: null,
        facebook: "https://www.facebook.com/profile.php?id=61572485499528",
        phone: null,
        googleSearch: null,
    },
    ]

export type TeamMember = (typeof teamMembers)[number]
