const WULWYN_AVATAR = "https://scontent.fmlw1-2.fna.fbcdn.net/v/t1.6435-9/53121401_10156204857453437_4904719181628309504_n.jpg?_nc_cat=110&ccb=1-7&_nc_sid=53a332&_nc_eui2=AeHM7VGP9lGvyVYSK7M-N7OPtyAmpe0yAEC3ICal7TIAQAlKnT9aru1Vra9ERu2ERftuf6IhMNQco4jjEhKBidka&_nc_ohc=SYJ_JtOEynwQ7kNvwEvzNt7&_nc_oc=Adr07kDph0gtEgDOQvhk0fPuJfD8yIQCW-tRlQntnwr2NJWgcB0da0ukKWRA-_lfK4s&_nc_zt=23&_nc_ht=scontent.fmlw1-2.fna&_nc_gid=leeCcpZhuqHH2j4XhF0Row&_nc_ss=7a32e&oh=00_AfzRDlNsrFWbsEoG0PgHvPw2I3IJDZvA7zUIBbRjWOgeCw&oe=69E7DA12"

/** Shown on /team/[id] for Monrovia Hustle voice cast — direction, tone, pipeline */
export type TeamMemberVoiceProfile = {
    design: string
    tone?: string
    pipeline?: string
}

function googleProfileSearch(query: string) {
    return `https://www.google.com/search?q=${encodeURIComponent(query)}`
}

export const teamMembers = [
    {
        id: "victor",
        name: "Victor Edet Coleman",
        role: "Founder & CTO",
        title: "Chief Technology Officer",
        badge: "01",
        image: "/Team/VICTOR.jpeg",
        photos: [
            { id: "01", image: "/Team/VICTOR.jpeg", caption: "CTO" },
        ],
        tagline: "3D Software Engineer · Founder & CTO of HUIX-2099",
        bio: "Chief Technology Officer driving HUIX-2099's technical vision. Architects and builds HUIX-HORIZEN and Virtual Past Liberia—platforms that enable Liberia and the region to imagine, prototype, and build the future through XR, 3D visualization, and immersive systems.",
        focus: "XR · 3D Visualization · Systems Architecture · AI Integration",
        location: "Monrovia, Liberia",
        email: "huixtech2099@gmail.com",
        status: "Technical Leadership · R&D · Product Architecture",
        linkedin: "https://www.linkedin.com/in/victor-coleman-4731701a5/",
        facebook: "https://www.facebook.com/victor.coleman.745874",
        phone: "+231776800064, +231887544923",
        googleSearch: "https://www.google.com/search?q=huix+2099+victor&oq=huix+2099+victor&gs_lcrp=EgZjaHJvbWUyBggAEEUYOTIGCAEQIxgnMgcIAhAAGO8FMgcIAxAAGO8FMgcIBBAAGO8FMgcIBRAAGO8FMgcIBhAAGO8F0gEINTg3OWowajeoAgCwAgA&sourceid=chrome&ie=UTF-8"
    },
    {
        id: "wulwyn",
        name: "Wulwyn Porte L",
        role: "CEO & Co-founder & Investor",
        title: "Chief Executive Officer",
        badge: "02",
        image: WULWYN_AVATAR,
        photos: [{ id: "01", image: WULWYN_AVATAR, caption: "CEO" }],
        tagline: "CEO & Co-founder · Strategic Lead & Investor",
        bio: "Chief Executive Officer steering HUIX-2099's business strategy and growth. Co-founder and lead investor driving partnerships, funding, and market expansion for Liberia's next-generation technology company.",
        focus: "Strategy · Business Development · Investment",
        location: "Monrovia, Liberia",
        email: "huixtech2099@gmail.com",
        status: "Executive Leadership · Partnerships · Growth",
        linkedin: null,
        facebook: null,
        phone: null,
        googleSearch: null
    },
    {
        id: "jboy",
        name: "Dominic Rockson",
        role: "Voice Actor · Jayboy",
        title: "Monrovia Hustle 3D — Jayboy (Jboy)",
        badge: "03",
        image: "/products/Monrovia_hustle_Demo_Campane/cast_concept/Dominc%20Rockson.png",
        photos: [
            {
                id: "01",
                image: "/products/Monrovia_hustle_Demo_Campane/cast_concept/CHARACTERS/JAYBOY.jpeg",
                caption: "Jayboy (in-fiction) · playable protagonist — Jboy / JBOY / JBoy in scripts",
            },
            {
                id: "02",
                image: "/products/Monrovia_hustle_Demo_Campane/cast_concept/Dominc%20Rockson.png",
                caption: "Dominic Rockson (voice talent)",
            },
        ],
        tagline: "Pride vs path · hustle or a legit lane",
        bio: "Jayboy (also written Jboy, JBOY, or JBoy in scripts and subtitles) is the main character you play in Monrovia Hustle 3D. He is a young man in Monrovia caught between family and the street. The intro sets him as proud: his mother tells him life is hard and to call Uncle Flomo for a real start; he answers that he does not need anybody and will make it himself. Ma's line \"Pride can make a man suffer\" is the story's hinge. Design notes frame him as not good versus evil but growing — learning to listen and pick a path with more purpose than noise. StoryState summarizes the arc as hustle versus a possible legit lane (Uncle / app-style work) and tags him as JBOY, age 24 in that autoload. Dominic Rockson voices Jayboy with the energy that carries both corner pride and the quieter beats when the script asks him to listen.",
        focus: "Voice · Playable protagonist · Street & family drama",
        location: "Monrovia, Liberia",
        email: "huixtech2099@gmail.com",
        status: "Voice Talent · HUIX Archive",
        linkedin: null,
        facebook: "https://www.facebook.com/profile.php?id=61572485499528",
        phone: null,
        googleSearch: googleProfileSearch("Dominic Rockson voice actor Jayboy Jboy Monrovia Hustle 3D Liberia HUIX-2099"),
        voiceProfile: {
            design: "Jayboy is written between family pull and street noise — pride versus Uncle Flomo's legit lane, hustle versus listening. Direction keeps reads playable: pride lands without cartoon bravado, doubt lands without losing forward motion.",
            tone: "Warm mid-register with street edge; Ma-and-Uncle scenes get room to breathe; mission spine stays lean.",
            pipeline: "Studio capture → light cleanup → Godot dialogue bus with ducking around street ambience so Jboy stays legible on foot and in hub beats.",
        },
    },
    {
        id: "arthur-kollie",
        name: "Arthur B. Kollie",
        role: "Voice Actor · Blamo",
        title: "Monrovia Hustle 3D — Blamo",
        badge: "04",
        image: "/products/Monrovia_hustle_Demo_Campane/cast_concept/Arthur%20B.%20Kollie.png",
        photos: [
            {
                id: "01",
                image: "/products/Monrovia_hustle_Demo_Campane/cast_concept/CHARACTERS/BLAMO.jpeg",
                caption: "Blamo (in-fiction) · smart-watch fence",
            },
            {
                id: "02",
                image: "/products/Monrovia_hustle_Demo_Campane/cast_concept/Arthur%20B.%20Kollie.png",
                caption: "Arthur B. Kollie (voice talent)",
            },
        ],
        tagline: "Smart-watch fence · street contact",
        bio: "Arthur B. Kollie voices Blamo in Monrovia Hustle 3D. Blamo is a street contact in Trapper's chain: after you finish the Tenneh button-phone run and Trapper takes his cut, Trapper sends you to Blamo with a smart watch. The mission script describes him as the \"smart-watch fence\" Trapper already set up with — pressure, receipts, and corner pragmatism in one read.",
        focus: "Voice · Street drama · Mission spine",
        location: "Monrovia, Liberia",
        email: "huixtech2099@gmail.com",
        status: "Voice Talent · HUIX Archive",
        linkedin: "https://www.linkedin.com/in/arthur-b-kollie-9b3592345/",
        facebook: "https://www.facebook.com/arthurbkollie",
        phone: null,
        googleSearch: googleProfileSearch("Arthur B Kollie voice actor Blamo Monrovia Hustle 3D HUIX-2099 Liberia"),
        voiceProfile: {
            design: "Blamo sits after the Tenneh phone thread — the hand-off when Trapper has already taken his cut and the watch has to move through someone who sounds like he has done this a hundred times. Direction leans controlled cool: short lines, confident timing, room for threat without cartoon villainy.",
            tone: "Measured street register; dry humour allowed; stakes land in pauses as much as volume.",
            pipeline: "Close-mic clarity for deal dialogue; light low-mid weight so lines read over street beds when the mission brings you out of pure phone UI.",
        },
    },
    {
        id: "david",
        name: "David Neor Jr.",
        role: "Voice Actor · DC (DC Young)",
        title: "Monrovia Hustle 3D — DC / DC Young",
        badge: "05",
        image: "/products/Monrovia_hustle_Demo_Campane/cast_concept/David%20Neor%20Jr.png",
        photos: [
            {
                id: "01",
                image: "/products/Monrovia_hustle_Demo_Campane/cast_concept/CHARACTERS/DC.jpeg",
                caption: "DC (in-fiction) · DC Young · Trapper's sneaker contact",
            },
            {
                id: "02",
                image: "/products/Monrovia_hustle_Demo_Campane/cast_concept/David%20Neor%20Jr.png",
                caption: "David Neor Jr. (voice talent)",
            },
        ],
        tagline: "Trapper's brother · sneaker contact on the chain",
        bio: "David Neor Jr. voices DC in Monrovia Hustle 3D — DC Young is another stop on the same Trapper-led street chain as the Tenneh button-phone run (TennehPhoneMission): Tenneh, Blamo, and the hand-offs between. In the script, Trapper's \"brother\" wants sneaker-level shine; DC is Trapper's sneaker contact. After the Blamo beat and Trapper's payout or split briefing, the mission sends you to deliver sneakers to him — tone, timing, and credibility still have to land like the rest of the chain.",
        focus: "Voice · Street chain · Sneaker beat",
        location: "Monrovia, Liberia",
        email: "huixtech2099@gmail.com",
        status: "Voice Talent · HUIX Archive",
        linkedin: null,
        facebook: "https://www.facebook.com/profile.php?id=61572485499528",
        phone: null,
        googleSearch: googleProfileSearch("David Neor Jr voice actor DC Young Monrovia Hustle 3D Trapper sneaker Liberia HUIX-2099"),
        voiceProfile: {
            design: "DC Young follows Blamo on the chain — energy from Trapper's briefing still in the room, but the beat shifts into sneaker culture and bro-familiarity with Trapper. Direction keeps him a real link in TennehPhoneMission logic, not a generic side quest.",
            tone: "Street-confident, quick warmth, sneaker-level flex without losing the payout thread.",
            pipeline: "Close-mic clarity for delivery and hand-off lines; level ride so DC reads over street beds when the player pulls up with the package.",
        },
    },
    {
        id: "johnett-s-talkpa",
        name: "Johnett S. Talkpa",
        role: "Voice Actor · Angel",
        title: "Monrovia Hustle 3D — Angel",
        badge: "06",
        image: "/products/Monrovia_hustle_Demo_Campane/cast_concept/Johnett%20S.%20Talkpa.png",
        photos: [
            {
                id: "01",
                image: "/products/Monrovia_hustle_Demo_Campane/cast_concept/CHARACTERS/angel.jpeg",
                caption: "Angel (in-fiction) · Jayboy's ex / love interest",
            },
            {
                id: "02",
                image: "/products/Monrovia_hustle_Demo_Campane/cast_concept/Johnett%20S.%20Talkpa.png",
                caption: "Johnett S. Talkpa (voice talent)",
            },
        ],
        tagline: "Love interest turned complicated · sharp in the club",
        bio: "Johnett S. Talkpa voices Angel in Monrovia Hustle 3D. Angel is Jayboy's ex and love interest — the emotional thread in his bedroom and later a sharp confrontation in the club. In StoryState she is described as a love interest turned complicated; in the club she has already broken up with him and is money-focused — not written as a cartoon villain, but not on his side emotionally anymore.",
        focus: "Voice · Romance thread · Club confrontation",
        location: "Monrovia, Liberia",
        email: "huixtech2099@gmail.com",
        status: "Voice Talent · HUIX Archive",
        linkedin: null,
        facebook: "https://www.facebook.com/profile.php?id=61572485499528",
        phone: null,
        googleSearch: googleProfileSearch("Johnett S Talkpa voice actor Angel Monrovia Hustle 3D HUIX-2099 Liberia"),
        voiceProfile: {
            design: "Angel bridges intimate bedroom beats and a harder club register — the same person, different safety. Direction keeps the turn believable: tenderness first, then boundaries that read as self-protection, not cruelty for sport.",
            tone: "Soft exhaustion at home; clipped clarity in the club when money and receipts are on the table.",
            pipeline: "Bedroom and comic beats stay close and dry; club confrontation gets a slightly brighter presence so the read cuts through crowd wash without going shrill.",
        },
    },
    {
        id: "thomas",
        name: "Thomas",
        role: "Street Operator · Connect",
        title: "Connect",
        badge: "07",
        image: "/products/Monrovia_hustle_Demo_Campane/images/WhatsApp%20Image%202026-05-04%20at%2011.57.51%20PM.jpeg",
        photos: [{ id: "01", image: "/products/Monrovia_hustle_Demo_Campane/images/WhatsApp%20Image%202026-05-04%20at%2011.57.51%20PM.jpeg", caption: "Thomas" }],
        tagline: "Fast talk, slower trust",
        bio: "Knows every shortcut between Broad and Benson; runs errands into favours — the kind that teach you downtown doesn't forgive noise. Expect branching missions that treat him like a hinge: help him, fleece him, or ghost him.",
        focus: "Logistics · Intelligence",
        location: "Monrovia, Liberia",
        email: "huixtech2099@gmail.com",
        status: "Operator · HUIX Archive",
        linkedin: null,
        facebook: "https://www.facebook.com/profile.php?id=61572485499528",
        phone: null,
        googleSearch: null
    },
    {
        id: "jonnet",
        name: "Jonnet",
        role: "Network · Pressure / Payoff",
        title: "Corner Memory",
        badge: "08",
        image: "/products/Monrovia_hustle_Demo_Campane/images/WhatsApp%20Image%202026-05-04%20at%2011.57.52%20PM.jpeg",
        photos: [{ id: "01", image: "/products/Monrovia_hustle_Demo_Campane/images/WhatsApp%20Image%202026-05-04%20at%2011.57.52%20PM.jpeg", caption: "Jonnet" }],
        tagline: "Corner memory",
        bio: "Holds rumours like currency — who owes, who flips phones, whose cousin heard Uncle Flomo's desk creak. Use her intel to stack LD or gamble reputation; epic beats land when alley gossip upgrades into storyline collision.",
        focus: "Information · Rumours",
        location: "Monrovia, Liberia",
        email: "huixtech2099@gmail.com",
        status: "Network · HUIX Archive",
        linkedin: null,
        facebook: "https://www.facebook.com/profile.php?id=61572485499528",
        phone: null,
        googleSearch: null
    },
    {
        id: "jerry-kollie",
        name: "Jerry D Kollie",
        role: "Voice Actor · Trapper",
        title: "Monrovia Hustle 3D — Trapper",
        badge: "09",
        image: "/products/Monrovia_hustle_Demo_Campane/cast_concept/Jerry%20D%20Kollie.png",
        photos: [
            {
                id: "01",
                image: "/products/Monrovia_hustle_Demo_Campane/cast_concept/CHARACTERS/Trapper.jpeg",
                caption: "Trapper (in-fiction) · street connect · TennehPhoneMission hub",
            },
            {
                id: "02",
                image: "/products/Monrovia_hustle_Demo_Campane/cast_concept/Jerry%20D%20Kollie.png",
                caption: "Jerry D Kollie (voice talent)",
            },
        ],
        tagline: "Gray hustle energy · opportunity and pressure",
        bio: "Jerry D Kollie voices Trapper in Monrovia Hustle 3D. Trapper is Jayboy's street connect — the one who gives him work, splits money, and moves product through other people (Tenneh, Blamo, DC Young, Musu). In StoryState he reads as \"street connect — opportunity and pressure\"; the club is his world (gray hustle energy), set against Uncle Flomo as the legit family path. On Broad Street, after the intro flow, he is the mission hub for TennehPhoneMission: he briefs Jayboy on the button phone for Tenneh, floor price, the smart watch hand-off for Blamo, the sneaker run, and Musu money; he takes his cuts, pays bonuses (for example LD after Blamo), then signs off with the cinema on Broad Street before the story pushes toward the club. In the club he is Jayboy's entry into the scene — the \"come meet my jue\" beat, walking the floor while he talks to her. Later he tells Jayboy that Ma called to check in, pushes \"family build, not noise\", and sends him to hear Uncle Flomo before the street wastes more time.",
        focus: "Voice · Mission hub · Street & club drama",
        location: "Monrovia, Liberia",
        email: "huixtech2099@gmail.com",
        status: "Voice Talent · HUIX Archive",
        linkedin: null,
        facebook: "https://www.facebook.com/profile.php?id=61572485499528",
        phone: null,
        googleSearch: googleProfileSearch("Jerry D Kollie voice actor Trapper Monrovia Hustle 3D TennehPhoneMission Liberia HUIX-2099"),
        voiceProfile: {
            design: "Trapper has to sell both opportunity and pressure — briefing beats stay tight (phones, floor price, watch, sneakers, Musu money), then the register drops when Ma or Uncle Flomo enters the conversation. Direction keeps him ahead of the player: confident, transactional, never a narrator.",
            tone: "Gray-hustle control room energy on Broad Street; club scenes open warmth and threat in the same breath.",
            pipeline: "Mission briefing lines ride slightly forward in the mix; club dialogue gets more air and softer tails so crowd beds can sit under him without burying the hook.",
        },
    },
    {
        id: "alfred-nyeswa",
        name: "Alfred M. Nyeswa",
        role: "Voice Actor · Jayboy Pa",
        title: "Monrovia Hustle 3D — Jayboy Pa (father)",
        badge: "11",
        image: "/products/Monrovia_hustle_Demo_Campane/cast_concept/Alfred%20M.%20Nyeswa.png",
        photos: [
            {
                id: "01",
                image: "/products/Monrovia_hustle_Demo_Campane/cast_concept/CHARACTERS/jayboy%20pa.jpeg",
                caption: "Jayboy Pa (in-fiction) · Jayboy's father — Pa",
            },
            {
                id: "02",
                image: "/products/Monrovia_hustle_Demo_Campane/cast_concept/Alfred%20M.%20Nyeswa.png",
                caption: "Alfred M. Nyeswa (voice talent)",
            },
        ],
        tagline: "LISTEN — good sense over pride",
        bio: "Alfred M. Nyeswa voices Jayboy Pa in Monrovia Hustle 3D. \"Pa\" means dad the way people often say it in Liberian English. Jayboy Pa is Jayboy's father — in the comic, the older man with the LISTEN speech bubble and serious, straight-talk energy: the parent figure trying to get Jayboy to actually hear good sense, not just flex pride.",
        focus: "Voice · Father · Comic & drama",
        location: "Monrovia, Liberia",
        email: "huixtech2099@gmail.com",
        status: "Voice Talent · HUIX Archive",
        linkedin: null,
        facebook: "https://www.facebook.com/profile.php?id=61572485499528",
        phone: null,
        googleSearch: googleProfileSearch("Alfred M Nyeswa voice actor Jayboy Pa father Monrovia Hustle 3D Liberia HUIX-2099"),
        voiceProfile: {
            design: "Jayboy Pa carries parental authority without theatre — love, fatigue, and frustration in one register. LISTEN beats stay plain-spoken: fewer words, heavier landing, so the comic bubble and VO match.",
            tone: "Grounded adult male; warmth under discipline; no sermon caricature.",
            pipeline: "Comic and bedroom lines print clearly; gentle compression so caps and bubble reads stay even next to music beds.",
        },
    },
    {
        id: "felix-sowoma",
        name: "Felix J. K. Sowoma",
        role: "Voice Actor · Uncle Flomo",
        title: "Monrovia Hustle 3D — Uncle Flomo",
        badge: "10",
        image: "/products/Monrovia_hustle_Demo_Campane/cast_concept/felix%20J.%20K.%20Sowoma.png",
        photos: [
            {
                id: "01",
                image: "/products/Monrovia_hustle_Demo_Campane/cast_concept/CHARACTERS/uncle_flomo.jpeg",
                caption: "Uncle Flomo (in-fiction) · family mentor · legit path",
            },
            {
                id: "02",
                image: "/products/Monrovia_hustle_Demo_Campane/cast_concept/felix%20J.%20K.%20Sowoma.png",
                caption: "Felix J. K. Sowoma (voice talent)",
            },
        ],
        tagline: "Legit help · receipts that can last",
        bio: "Felix J. K. Sowoma voices Uncle Flomo in Monrovia Hustle 3D. Uncle Flomo is Jayboy's uncle — the family mentor Ma keeps steering Jayboy toward: legit help, straight talk, and a path off the street (work, receipts, something that can last), set against Trapper's hustle-and-club world. You meet him in the office scene: he has been waiting while Jayboy stayed outside; he is direct about Ma asking for help and the choice between a better life versus hustling for nothing, then invites him in when Jayboy finally enters. Jayboy apologizes and says he is ready to listen and change — the slice's emotional landing before the thank-you screen.",
        focus: "Voice · Mentor · Office scene",
        location: "Monrovia, Liberia",
        email: "huixtech2099@gmail.com",
        status: "Voice Talent · HUIX Archive",
        linkedin: null,
        facebook: "https://www.facebook.com/profile.php?id=61572485499528",
        phone: null,
        googleSearch: googleProfileSearch("Felix J K Sowoma voice actor Uncle Flomo Monrovia Hustle 3D Jayboy mentor Liberia HUIX-2099"),
        voiceProfile: {
            design: "Uncle Flomo is the legit counterweight to Trapper — same city, different gravity. Office scene direction stays patient then firm: he has already waited; the read earns the apology beat without melodrama.",
            tone: "Calm authority, slower cadence than street voices; hope without softening the cost of the choice.",
            pipeline: "Dry office ambience; voice sits forward with light room tone so Ma/help talk stays intimate on close framing.",
        },
    },
    {
        id: "quinn-win-liberia",
        name: "Quinn",
        role: "Friend · office space for the prototype",
        title: "Win Liberia — space to build Monrovia Hustle 3D",
        badge: "11",
        image: "/Team/quinn-huix-partner.svg",
        photos: [{ id: "01", image: "/Team/quinn-huix-partner.svg", caption: "Quinn — friend who shared office space for the prototype" }],
        tagline: "Our friend Quinn gave HUIX a room to build — not software access, not a vendor login — real desk space.",
        bio: "Quinn is a friend of the studio, not a code package or an “access SKU.” He opened office space so HUIX-2099 could build the Monrovia Hustle 3D prototype with a door that closes and a desk that stays put. We still talk about Win Liberia / Cread on the build because that is the lane we file work under — but the human story is simpler: a friend trusted us with space. This page is a thank-you and a straight credit line; swap the portrait when Quinn is happy with a photo.",
        focus: "Office space · prototype build · Win Liberia (friend network)",
        location: "Liberia",
        email: "huixtech2099@gmail.com",
        status: "Friend & space supporter · HUIX Archive",
        linkedin: null,
        facebook: null,
        phone: null,
        googleSearch: null,
    },
    ]

export type TeamMember = (typeof teamMembers)[number]
